- name: Register Current User for i3
  shell: whoami
  register: current_user
  tags: &tags_for_i3_tasks ['i3', 'desktop'] 

- name: Install i3
  become: true
  apt:
    name: ["i3", "menu", "xorg", "xclip", "light"]
  tags: *tags_for_i3_tasks 

- name: Install Papirus Icon Theme
  become: true
  apt: name=papirus-icon-theme
  tags: *tags_for_i3_tasks

- name: Install Power Manager
  become: true
  apt: name=xfce4-power-manager
  tags: *tags_for_i3_tasks

- name: Install Polybar
  become: true
  apt: name=polybar
  tags: *tags_for_i3_tasks 

- name: Install feh
  become: true
  apt: name=feh
  tags: *tags_for_i3_tasks 

- name: Install arandr
  become: true
  apt: name=arandr
  tags: *tags_for_i3_tasks 

- name: Install rofi
  become: true
  apt: name=rofi
  tags: *tags_for_i3_tasks 

- name: Install flameshot
  become: true
  apt: name=flameshot
  tags: *tags_for_i3_tasks 

- name: Install thunar
  become: true
  apt: name=thunar
  tags: *tags_for_i3_tasks 

- name: Install Pulse-Audio & Tools
  become: true
  apt:
    name: ["pulseaudio", "pavucontrol", "playerctl"]
  tags: *tags_for_i3_tasks

- name: Add User to video group
  become: true
  shell: usermod -aG video {{ current_user.stdout }}
  tags: *tags_for_i3_tasks

