- name: Add Liquorix Dependencies
  become: true
  apt:
    name: ['gpg', 'ca-certificates', 'apt-transport-https'] 
  tags: &tags_for_kernel_tasks ['kernel', 'desktop'] 

- name: Add Liquorix Keys
  become: true
  shell: curl 'https://liquorix.net/liquorix-keyring.gpg' | gpg --batch --yes --output '/etc/apt/keyrings/liquorix-keyring.gpg' --dearmor
  tags: *tags_for_kernel_tasks

- name: Add Liquorix Repository 
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/liquorix-keyring.gpg] https://liquorix.net/debian/ bookworm main
    state: present
  tags: *tags_for_kernel_tasks

- name: Update Liquorix APT 
  become: true
  apt:
    force_apt_get: true
    update_cache: yes
    state: present
  tags: *tags_for_kernel_tasks

- name: Install Liquorix Kernel
  become: true
  apt:
    name: ['linux-image-liquorix-amd64', 'linux-headers-liquorix-amd64']
    state: latest
  tags: *tags_for_kernel_tasks

- name: Clean old Kernel 
  become: true
  apt:
    autoremove: yes
    purge: yes
  tags: *tags_for_kernel_tasks
