- name: Install Openbox
  become: true
  apt:
    name: ["openbox", "menu", "xorg"]
  tags: &tags_for_openbox_tasks ['openbox', 'desktop'] 

- name: Install Polybar
  become: true
  apt: name=polybar
  tags: *tags_for_openbox_tasks 

- name: Install lightdm
  become: true
  apt: name=lightdm
  tags: *tags_for_openbox_tasks 

- name: Install feh
  become: true
  apt: name=feh
  tags: *tags_for_openbox_tasks 

- name: Install arandr
  become: true
  apt: name=arandr
  tags: *tags_for_openbox_tasks 

- name: Install rofi
  become: true
  apt: name=rofi
  tags: *tags_for_openbox_tasks 
