- name: Register Current User for Openbox
  shell: whoami
  register: current_user
  tags: &tags_for_openbox_tasks ['openbox', 'desktop'] 

- name: Install Openbox
  become: true
  apt:
    name: ["openbox", "menu", "xorg", "xclip", "light"]
  tags: *tags_for_openbox_tasks 

- name: Install Papirus Icon Theme
  become: true
  apt: name=papirus-icon-theme
  tags: *tags_for_openbox_tasks

- name: Install Power Manager
  become: true
  apt: name=xfce4-power-manager
  tags: *tags_for_openbox_tasks

- name: Install Polybar
  become: true
  apt: name=polybar
  tags: *tags_for_openbox_tasks 

- name: Install feh
  become: true
  apt: name=feh
  tags: *tags_for_openbox_tasks 

- name: Install arandr
  become: true
  apt: name=arandr
  tags: *tags_for_openbox_tasks 

- name: Install rofi
  become: true
  apt: name=rofi
  tags: *tags_for_openbox_tasks 

- name: Install ksnip
  become: true
  apt: name=ksnip
  tags: *tags_for_openbox_tasks 

- name: Install thunar
  become: true
  apt: name=thunar
  tags: *tags_for_openbox_tasks 

- name: Install Pulse-Audio & Tools
  become: true
  apt:
    name: ["pulseaudio", "pavucontrol", "playerctl"]
  tags: *tags_for_openbox_tasks

- name: Add User to video group
  become: true
  shell: usermod -aG video {{ current_user.stdout }}
  tags: *tags_for_openbox_tasks

