- hosts: localhost
  vars:
    source_key: "./ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
  - name: Update and upgrade apt packages
    become: true
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 # One Day
    tags:
      - install
      - core
      - desktop
  tasks:
    - include: tasks/core.yml
    - include: tasks/ssh.yml
    - include: tasks/neovim.yml
    - include: tasks/zsh.yml
    - include: tasks/dotfiles.yml
    - include: tasks/kitty.yml
    - include: tasks/kiboigo.yml
    - include: tasks/openbox.yml
    - include: tasks/rust.yml
