- hosts: localhost
  vars:
    source_key: "./ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
  - name: Update and upgrade apt packages
    become: true
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 # One Day
    tags:
      - core
      - desktop
  tasks:
    - include: tasks/core/core.yml
    - include: tasks/core/ssh.yml
    - include: tasks/core/zsh.yml
    - include: tasks/core/dotfiles.yml
    - include: tasks/kiboigo.yml
    - include: tasks/dev/neovim.yml
    - include: tasks/dev/rust.yml
    - include: tasks/desktop/kernel.yml
    - include: tasks/desktop/openbox.yml
    - include: tasks/desktop/ly.yml
    - include: tasks/desktop/fonts.yml
    - include: tasks/desktop/flatpak.yml
    - include: tasks/apps/firefox.yml
    - include: tasks/apps/kitty.yml
    - include: tasks/apps/discord.yml
    - include: tasks/apps/spotify.yml
    - include: tasks/apps/slack.yml
