- hosts: localhost
  vars:
    source_key: "./ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    gpg_private_source: "./gnupg/private_key.asc"
    gpg_public_source: "./gnupg/public_key.asc"
  pre_tasks:
  - name: Update and upgrade apt packages
    become: true
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 # One Day
    tags:
      - core
      - desktop
  tasks:
    - include: tasks/core/core.yml
    - include: tasks/core/ssh.yml
    - include: tasks/core/gnupg.yml
    - include: tasks/core/zsh.yml
    - include: tasks/core/dotfiles.yml
    - include: tasks/kiboigo.yml
    - include: tasks/dev/neovim.yml
    - include: tasks/desktop/kernel.yml
    - include: tasks/desktop/i3.yml
    - include: tasks/desktop/ly.yml
    - include: tasks/desktop/fonts.yml
    - include: tasks/desktop/flatpak.yml
    - include: tasks/apps/firefox.yml
    - include: tasks/apps/krita.yml
    - include: tasks/apps/kitty.yml
    - include: tasks/apps/discord.yml
    - include: tasks/apps/spotify.yml
    - include: tasks/apps/steam.yml
    - include: tasks/apps/slack.yml
    - include: tasks/apps/freecad.yml
    - include: tasks/apps/kicad.yml
    - include: tasks/dev/rust.yml
    - include: tasks/dev/virt.yml
    - include: tasks/dev/java.yml
    - include: tasks/dev/node.yml
    - include: tasks/dev/dotnet.yml
    - include: tasks/dev/docker.yml
    - include: tasks/dev/k3s.yml
    - include: tasks/dev/hotspot.yml
