- name: Register Current User for Docker
  shell: whoami
  register: current_user
  tags: &tags_for_docker_tasks ['docker', 'k3s', 'dev']

- name: Add Docker GPG Apt Key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
    force: true
  tags: *tags_for_docker_tasks

- name: Add Docker Apt
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/debian/ bookworm stable
    state: present
  tags: *tags_for_docker_tasks

- name: Install Docker
  become: true
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-buildx-plugin', 'docker-compose-plugin']
    state: latest
    update_cache: true
  tags: *tags_for_docker_tasks

- name: Add User to Docker group
  become: true
  shell: usermod -aG docker {{ current_user.stdout }}
  tags: *tags_for_docker_tasks
