- name: Add Node Repository
  become: true
  shell: curl -fsSL https://deb.nodesource.com/setup_20.x | bash - 
  tags: &tags_for_node_tasks ['node', 'dev']

- name: Install Node 20
  become: true
  apt: name=nodejs
  tags: *tags_for_node_tasks

- name: Install pnpm
  become: true
  shell: npm install -g pnpm
  tags: *tags_for_node_tasks
