- name: Check that Zigup Exists 
  stat:
    path: "{{ lookup('env', 'HOME') }}/.local/bin/zigup"
  register: zigup_file
  tags: &tags_for_zig_tasks ['zig', 'dev', 'desktop', 'ly']

- name: Create .local/bin
  shell: mkdir -p {{ lookup('env', 'HOME') }}/.local/bin
  when: zigup_file.stat.exists == false
  tags: *tags_for_zig_tasks

- name: Install Zigup
  shell: curl -L https://github.com/marler8997/zigup/releases/download/v2024_05_05/zigup-x86_64-linux.tar.gz | tar -xvzf - -C {{ lookup('env', 'HOME') }}/.local/bin/ 
  when: zigup_file.stat.exists == false
  tags: *tags_for_zig_tasks

- name: Install Zig
  shell: "{{ lookup('env', 'HOME') }}/.local/bin/zigup 0.12.0"
  when: zigup_file.stat.exists == false
  tags: *tags_for_zig_tasks
