- name: Ensure .kiboigo directory exists.
  file:
    dest: "{{ $HOME/.kiboigo }}"
    mode: 0700
    state: directory
  tags: &tags_for_kiboigo_tasks [ 'install', 'kiboigo' ]

- name: Install Kiboigo ZSH
  copy:
    src: "./kiboigo/kiboigo.zsh"
    dest: "$HOME/.kiboigo/kiboigo.zsh"
    mode: 0600
  tags: *tags_for_kiboigo_tasks
