- name: Ensure .kiboigo directory exists.
  file:
    dest: "{{ lookup('env', 'HOME') }}/.kiboigo"
    mode: 0700
    state: directory
  tags: &tags_for_kiboigo_tasks ['kiboigo', 'desktop', 'dev']

- name: Install Kiboigo ZSH
  copy:
    src: "./kiboigo/kiboigo.zsh"
    dest: "{{ lookup('env', 'HOME') }}/.kiboigo/kiboigo.zsh"
    mode: 0600
  tags: *tags_for_kiboigo_tasks
