- name: Install Firefox 
  become: true
  apt: name=firefox-esr
  tags: ['firefox', 'desktop']

- name: Set Firefox as default Browser 
  become: true
  shell: update-alternatives --set x-www-browser /usr/bin/firefox-esr
  tags: ['firefox', 'desktop']
