- name: Install Kitty 
  become: true
  apt: name=kitty
  tags: ['kitty', 'desktop']

- name: Set Kitty as default Terminal
  become: true
  shell: update-alternatives --set x-terminal-emulator /usr/bin/kitty
  tags: ['kitty', 'desktop']

- name: Download JetBrainsMono Nerd Font
  shell: curl -L https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/JetBrainsMono.zip -o {{ lookup('env', 'HOME') }}/JetBrainsMono.zip
  tags: ['fonts', 'desktop']

- name: Install JetBrainsMono Nerd Font
  shell: unzip {{ lookup('env', 'HOME') }}/JetBrainsMono.zip -d {{ lookup('env', 'HOME') }}/.fonts/ && fc-cache && rm {{ lookup('env', 'HOME') }}/JetBrainsMono.zip
  tags: ['fonts', 'desktop']
