- name: System Packages [Base]
  become: true
  apt:
    name: ["curl", "build-essential", "make", "cmake", "zip", "unzip", "autoconf", "automake", "g++", "pkg-config", "doxygen", "ninja-build", "gettext", "libtool", "libtool-bin"]
  tags: ['core', 'desktop', 'neovim']

- name: Network Manager
  become: true
  apt: name=network-manager
  tags: ['core', 'desktop']

- name: firewalld
  become: true
  apt: name=firewalld
  tags: ['core', 'desktop']

- name: Gnome Keyring 
  become: true
  apt: name=gnome-keyring
  tags: ['core', 'desktop']
