- name: Installing stow
  apt: name=stow
  become: true
  tags: &tags_for_df_tasks ['dotfiles', 'core', 'desktop']

- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:mistermuki/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    update: yes
    accept_hostkey: yes
    version: main
  tags: *tags_for_df_tasks 

- name: Check that .zshrc exists
  stat:
    path: /home/{{ current_user.stdout}}/.zshrc
  register: zshrc_file
  tags: *tags_for_df_tasks 

- name: Remove .zshrc
  shell: rm ~/.zshrc
  when: zshrc_file.stat.exists == true
  tags: *tags_for_df_tasks 

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./install.sh
  tags: *tags_for_df_tasks
