- name: Register Current User for ZSH
  shell: whoami
  register: current_user
  tags: always 

- name: Install ZSH
  apt: name=zsh
  become: true
  tags: always
    
- name: Change shell to zsh
  become: true
  shell: chsh -s $(which zsh) {{ current_user.stdout }}
  tags: always

- name: Check that the somefile.conf exists
  stat:
    path: /home/{{ current_user.stdout}}/.oh-my-zsh
  register: oh_my_stats
  tags: always

- name: Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  tags: always
  when: oh_my_stats.stat.exists == false
  become_user: muki 

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags: always
